### ISSUE TITLE
Custom dataset preprocessing using fairseq

### ISSUE THREAD

**Issue by MarkDeng1** [AnonymousAKES/Differentially-Private-Fine-tuning-of-Language-Models#5]
I want to use my own 'xxx.jsonl' file as the training data. 

Could you please indicate how did your process your SST-2-bin before? 

Thanks,
Mark

**Comment by dayu11** [comment]
Hi Mark,

Thank you for your question! We use [this script](https://github.com/facebookresearch/fairseq/blob/main/examples/roberta/README.glue.md) from the Fairseq repo for preprocessing the data. 


Best,
Da
